### PR TITLE
Remove unused setting operator name

### PR DESCRIPTION
**Pull request by tydanielson**
This is what through me off when I was trying to figure out how to set the message writer... name isn't even passed into this function.  So to not through off others might as well just remove the useless code.

### CODE REVIEW

**Comment by boldwade** [comment]
Hi Ty, this element is actually used in the Hubris theme. I'm going to go ahead and deny this PR.

**Comment by tydanielson** [comment]
The hubris theme sets the value in `addOrUpdateMessage` not in the `initializeMessageElement` function and `name` isn't passed into it anyways.

```
this.initializeMessageElement = function(messageElement, messageId, personType, time, avatar) 
```

**Comment by boldwade** [comment]
Indeed, this appears to be a bug. The name is null and should be populated with the name of the operator. Will put a fix out shortly. Thanks Ty. The Hubris theme sets the name of the operator in the title, next to the 'Chat with' text. So that is where it's trying to set the name of the operator. Whereas, the other themes set the name in each chat bubble. You may be right, in that the addOrUpdateMessage may be where we'll update the actual header for the hubris theme. Not sure yet.

**Comment by boldwade** [comment]
The fix for this was just to add name to the initializeMessageElement signature and pass name from addOrUpdateMessage.

**Comment by tydanielson** [comment]
Ok that makes sense.  I did do that when I was working with it initially and ran into some issues where it would set the field only after at least 2 messages from either the operator or the client were created.  As long as this is only for the title I dont' think it will be an issue.  This did give me the runaround so some extra comments about it would be awesome.  Thanks Wade.

**Pull request closed without merging**
